# Generated by Django 3.2 on 2021-04-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkyoutube',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
    ]
