# Generated by Django 3.2 on 2021-05-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_youtube', '0002_bookmarkyoutube_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkyoutube',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified'),
        ),
    ]
